### ISSUE TITLE
Fix Trakt Authorization dialog on Trakt.tv

### ISSUE THREAD

**Issue by drinfernoo** [I-A-C/plugin.video.exodusredux#15]
This isn't something in THIS add-on, but the fact that Exodus Redux comes up on Trakt.tv as "Test" with no icon, whenever we try to authorize it.

**Comment by I-A-C** [comment]
That does look a little sketchy..  I'll have to look into that.

**Comment by drinfernoo** [comment]
@I-A-C It's very easym You can edit it directly on Trakt.tv, and it updates immediately.

**Comment by I-A-C** [comment]
I didn't have authority over the current Trakt API key, so I created a new trakt API key with icon and named ExodusRedux. If I upload a new Trakt API key, will that adversely affect the current installed user base or will it be as easy as reauthorizing?

**Comment by doko-desuka** [comment]
If the user has a cached token from a previous use, it'll be for the old API key.  
When the user tries to go into their Trakt manager, it'll try to use this cached token but with the new key.
It'll keep failing in an obscure way, because the code sees that there's a cached token and assumes that it should definitely work with the key and will keep trying to do that.  
It doesn't have a failsafe at the moment.

**Comment by drinfernoo** [comment]
In other words, users will have to reauthorize.

**Comment by doko-desuka** [comment]
Did anyone test it with the new API key? What are you getting?

**Comment by drinfernoo** [comment]
Is there a new API key? I only update whenever it hits the repo.

**Comment by doko-desuka** [comment]
I think so, there's a commit from Nov 15 on script.module.exodusredux:  
https://github.com/I-A-C/script.module.exodusredux/commit/288de8330f3954b279e6e745848dede1275c7681

**Comment by drinfernoo** [comment]
The changes went live in the repo today.
