### ISSUE TITLE
Make "Info!!" Popup on first run or after a update 

### ISSUE THREAD

**Issue by SerpentDrago** [I-A-C/plugin.video.exodusredux#16]
I feel this would help a great many people that can't seem to figure out anything on their own lol . 

Thanks for all your work ! you don't get enough thanks !

**Comment by I-A-C** [comment]
Lemme ask you a question.  What is it? Are the instructions unclear?  I really hate putting blame on the end-user, but sometimes I just don't know. 

I realize the 3 steps it took to get everything working was too much for many users.  Now that everything is default, I'm not sure what more I can do to make things easier.  I'd imagine if someone wants everything done for them they'd use reaper's build which is Lambdascrapers integrated.

As for "Info!! on first run popup, that a good idea.  An unnamed addon's abuse of the popup(systemwide and in addon) left such a bad taste that I never even considered it.

**Comment by SerpentDrago** [comment]
Dude , i agree man , I think most of the issue seems to be from botched upgrades somehow . But regular folks + kodi just doesn't seem to mix . 

is everything really default now both in redux and lambada ? is there ANYTHING required on first install ? I prob should test that sometime .  If so that will help A LOT . 

You just keep making improvements man !@ , i'll keep relaying issues i think have solutions . Dont' worry about the end users to much we will handle that on A4k !

**Comment by SerpentDrago** [comment]
Also check your PM's on reddit man ! sent you something

**Comment by 13Clowns** [comment]
Man the scrappers are great. People don't read, they want install and go. How bad was it when people tried to learn how to pair RD. That all this is. In time it will be fine.

**Comment by I-A-C** [comment]
@SerpentDrago,I'm a reddit lurker by habit .  I get a lot totally random and stupid PM's and my instinct is to ignore them.  I have to adjust to being an active participant.  I'm one of those people who gravitated to reddit because I wasn't in to the whole friends/social media scene.   I guess I gotta do the friends thing on reddit to make sure I get the important stuff.

Everything should default in both.  So if things are really screwy, hitting the Default button at the bottom of the "Settings - ExodusRedux" and "Settings - Lambdascrapers Module" windows should straighten everything out; with the obvious downside that prior settings modifications would be lost.

**Comment by SerpentDrago** [comment]
Well check the pm i sent you 6 days ago ,
