### ISSUE TITLE
Up Next Integration 

### ISSUE THREAD

**Issue by SerpentDrago** [I-A-C/plugin.video.exodusredux#19]
This would be a cool feature to include if someone wants to do it .  Integration instructions for Addons is included in these links

https://forum.kodi.tv/showthread.php?tid=336747

https://github.com/im85288/service.upnext/wiki

**Comment by Tikipeter** [comment]
I've had a go at this, but I found the upnext service a bit temperamental.

Below is a new `player.py` file with the most basic of integration for upnext (i.e. if it's an episode playing, upnext will activate).

It's a simple process to add settings for turning it off, how long before the end before it activates etc (at the moment it is 2min before the end for testing purposes).

I was thinking perhaps it should only be available when autoplay is turned on, otherwise it won't 'autoplay' the next episode, it will just trigger an automatic scraping of the next episode.

As well as replacing the `player.py` file with the one below, also add the AddonSignals dependency to the `addon.xml` file in `plugin.video.exodusredux` i.e. put the code below inside of the `<requires>` tags:

    <import addon="script.module.addon.signals" version="0.0.1"/>


https://pastebin.com/kJRnXyeE

If someone can test this then we can go from there.

Unfortunately, pre-emptive scraping for a more seamless experience will require some work to be done in the `sources.py` file. But, I think it might be doable even with my very limited skills, so a skilled coder would probably not have much of an issue with it.
