### ISSUE TITLE
Bungled titles on widget items

### ISSUE THREAD

**Issue by drinfernoo** [I-A-C/plugin.video.exodusredux#24]
Not sure exactly what is going on here, but it appears that on the latest version, titles on widget items are formatted in some weird way.

The first two images in this album are from widgets populated by Exodus Redux, while the second two are from another add-on.

https://imgur.com/a/1YhfKeB

**Comment by SerpentDrago** [comment]
Widgets pointed to a Redux > Trakt List correct ? that info could be helpfull

**Comment by host505** [comment]
What skin is this? I checked Confluence and can't repoduce (Estuary doesn't have widget titles).
Are you sure this occurred only since the last update?
I'm suspecting [this](https://github.com/I-A-C/script.module.exodusredux/commit/8ecaad44e5d9860d0b824dbb95b07fad3e4f51ac), can you try to comment-out [that line](https://github.com/I-A-C/script.module.exodusredux/blob/master/lib/resources/lib/indexers/tvshows.py#L1073)?

**Comment by drinfernoo** [comment]
@SerpentDrago Indeed, from a Trakt list. My bad.

**Comment by drinfernoo** [comment]
@host505 I'm sure it's just since the latest build, as it isn't doing this on my Shield, on a previous build. The skin is Aura, in both cases.

**Comment by Tikipeter** [comment]
host505 is most likely right about it being the cause of the incorrect labeling.

Even if it's not the cause, the suspected line should be:

    meta.update({'tvshowtitle': i['originaltitle']})

This is my fault when trying to fix Extended Info for TV Shows.
I didn't take anywhere near enough notice of the variable I used.

Sorry. :( :( :(

**Comment by drinfernoo** [comment]
@Tikipeter Probably should be just 'title' or 'name', rather than 'originaltitle', then?

**Comment by host505** [comment]
I couldn't reproduce with aura skin. Does this occur with Kodi 17 or 18?
@drinfernoo can you replace line 1073 of tvshows.py with the one suggested by Tikipeter?

**Comment by Tikipeter** [comment]
@drinfernoo  'title' and 'originaltitle' are always the same, so it could be either.

There is no 'name' key though, so don't change it to that.

**Comment by jewbmx** [comment]
Omg so 2mins of looking at those pics and i finally spot the titles and figure out i dont need to open them from the page lol then i toss down my phone for a minute to eat a burger and start tryin to swipe thru like its a damn movie site or netflix lmao. Think imma goto bed or stop smokin.

Also like to note that originaltitle should be the best choice in the long run but thats debatable due to some crappy labeling for some stuff you find.
